#!/usr/bin/env python3
# Author: Johanna Girodolle

"""Constants used by the region overview generator."""

TRACK_HEIGHT = 28
FEATURE_HEIGHT = 22
SNP_HEIGHT = 20
TRACK_Y_OFFSET = 12
PANEL_BOTTOM_SPACE = 12
PANEL_HEIGHT = TRACK_Y_OFFSET + TRACK_HEIGHT + PANEL_BOTTOM_SPACE
PANEL_GAP = 6
LEFT_MARGIN = 110
RIGHT_MARGIN = 40
TOP_MARGIN = 52
BOTTOM_MARGIN = 30
SNP_LINE_WIDTH = 1
VIEWER_MIN_WIDTH = 900
SIDEBAR_WIDTH = 320
