#!/usr/bin/env python3
# Author: Johanna Girodolle

"""Constants used by the region overview generator."""

TRACK_HEIGHT = 28
FEATURE_HEIGHT = TRACK_HEIGHT - 2
SNP_HEIGHT = TRACK_HEIGHT
TRACK_Y_OFFSET = 12

PANEL_BOTTOM_SPACE = 12
PANEL_HEIGHT = TRACK_Y_OFFSET + TRACK_HEIGHT + PANEL_BOTTOM_SPACE
PANEL_GAP = 6

VIEWER_TOP_UI_HEIGHT = 44

LEFT_MARGIN = 110
RIGHT_MARGIN = 40
TOP_MARGIN = 30
BOTTOM_MARGIN = 30
END_PADDING_PX = 24

SNP_LINE_WIDTH = 2

VIEWER_MIN_WIDTH = 900
SIDEBAR_WIDTH = 320

# Zoom behaviour
TARGET_VISIBLE_BP = 2_000
ZOOM_STEPS = 16
MAX_ZOOM_CAP = 10000

# Axis behaviour
TARGET_TICK_SPACING_PX = 100
BP_TO_KB_THRESHOLD_BP = 10_000
KB_TO_MB_THRESHOLD_BP = 1_000_000

# Features
BLOCK_MIN_WIDTH_PX = 1
BLOCK_HIGHLIGHT_MIN_WIDTH_PX = 2
SNP_MIN_WIDTH_PX = 1
SNP_HIGHLIGHT_MIN_WIDTH_PX = 2

# Colors
BLOCK_FILL = "#d9d9d9"
SNP_COLOR = "#d62728"
PIN_HIGHLIGHT_COLOR = "rgb(0,120,255)"
HOVER_HIGHLIGHT_COLOR = "#93c5fd"


SIDEBAR_MIN_WIDTH = 260
SIDEBAR_MAX_WIDTH_RATIO = 0.7
RESIZER_WIDTH = 8
