samples: dev/integration_case_builder/dataset/generated/samples.tsv
outdir: results

sibeliaz:
  min_block_len: 30

block_filtering:
  min_len: 450

repeat_masking:
  te_lib: ".tests/integration/resources/mini_TE_lib.fasta"

mafft:
  extra_options: "" #--genafpair --maxiterate 1000

snp_detection:
  min_flank: 0 #100

snp_group_filtering:
  group_a:
    - Karur
  group_b:
    - Soldur
