samples: dev/integration_case_builder/dataset/generated/samples.tsv
outdir: results

sibeliaz:
  min_block_len: 30

filtering:
  min_len: 450

mafft:
  extra_options: "" #--genafpair --maxiterate 1000

te_lib: dev/integration_case_builder/dataset/TE_lib/trep-db_complete_Rel-19.fasta
