samples: samples.tsv
outdir: results

sibeliaz:
  min_block_len: ""

block_filtering:
  min_len: ""

repeat_masking:
  te_lib: ""

mafft:
  extra_options: ""

snp_detection:
  min_flank: ""

snp_group_filtering:
  group_a: []
  group_b: []
