executor: slurm
jobs: 20
latency-wait: 60
printshellcmds: true
rerun-incomplete: true
seconds-between-status-checks: 1
slurm-init-seconds-before-status-checks: 5

default-resources:
  slurm_account: "dedicated-cpu@cirad-normal"
  slurm_partition: "cpu-dedicated"
  runtime: "1h"

set-threads:
  run_sibeliaz: 1

set-resources:
  run_sibeliaz:
    mem_mb: 20000
  run_pairwise_minimap2:
    mem_mb: 10000
